In [96]:
# auto-reload changes to imported modules
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [97]:
import compile_tables as ct
import compile_file as cf
import parser_dat as p

In [98]:
db_list = p.phreeqc_database_list('../databases/test_data')
print(db_list)
mst = ct.compile_master_solution_table(db_list)
sp = ct.compile_solution_species_table(db_list)
phases = ct.compile_phase_table(db_list)

['../databases/test_data/phreeqc.dat']

In [99]:
mst.head()

  element species   alk gfw_formula element_gfw        source
0       H      H+  -1.0           H       1.008  #phreeqc.dat
1    H(0)      H2     0           H        None  #phreeqc.dat
2   H(+1)      H+  -1.0           0        None  #phreeqc.dat
3       E      e-     0         0.0           0  #phreeqc.dat
4       O     H2O     0           O        16.0  #phreeqc.dat

In [100]:
sp.head()

,equation,log_k,delta_h,gamma,d_w,v_m,source
0,2 H2O = O2 + 4 H+ + 4 e-,-86.080,"(134.79, kcal)",None,"(2.35e-09,)","(5.7889, 6.3536, 3.2528, -3.0417, -0.3943)",phreeqc.dat
1,2 H+ + 2 e- = H2,-3.150,"(-1.759, kcal)",None,"(5.13e-09,)","(6.52, 0.78, 0.12)",phreeqc.dat
2,CO3-2 + H+ = HCO3-,10.329,"(-3.561, kcal)","(5.4, 0)","(1.18e-09, 0.0, 1.43, 1e-10)","(8.472, 0.0, -11.5, 0.0, 1.56, 0.0, 0.0, 146.0...",phreeqc.dat
3,CO3-2 + 2 H+ = CO2 + H2O,16.681,"(-5.738, kcal)",None,"(1.92e-09,)","(7.29, 0.92, 2.07, -1.23, -1.6)",phreeqc.dat
4,2CO2 = (CO2)2,-1.800,None,None,None,"(14.58, 1.84, 4.14, -2.46, -3.2)",phreeqc.dat

In [101]:
phases.head()

,phase_name,dissolution_reaction,log_k,delta_h,analytic,v_m,t_c,p_c,omega,source
0,Calcite,CaCO3 = CO3-2 + Ca+2,-8.48,"(-2.297, kcal)","(17.118, -0.046528, -3496)","(36.9, cm3/mol)",None,None,None,phreeqc.dat
1,Aragonite,CaCO3 = CO3-2 + Ca+2,-8.336,"(-2.589, kcal)","(-171.9773, -0.077993, 2903.293, 71.595)","(34.04,)",None,None,None,phreeqc.dat
2,Dolomite,CaMg(CO3)2 = Ca+2 + Mg+2 + 2 CO3-2,-17.09,"(-9.436, kcal)","(31.283, -0.0898, -6438)","(64.5,)",None,None,None,phreeqc.dat
3,Siderite,FeCO3 = Fe+2 + CO3-2,-10.89,"(-2.480, kcal)",None,"(29.2,)",None,None,None,phreeqc.dat
4,Rhodochrosite,MnCO3 = Mn+2 + CO3-2,-11.13,"(-1.430, kcal)",None,"(31.1,)",None,None,None,phreeqc.dat

In [102]:
phases[phases['phase_name'] == 'H2O(g)']

,phase_name,dissolution_reaction,log_k,delta_h,analytic,v_m,t_c,p_c,omega,source
44,H2O(g),H2O = H2O,1.506,"(-44.03, kJ)","(-16.5066, -2.0013E-3, 2710.7, 3.7646, 0, 2.24...",None,647.3,217.6,0.344,phreeqc.dat

In [ ]:
import